Authentication/urls.py
# Authentication/urls.py

from . import views
from django.urls import path

app_name = 'Authentication'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('verify_email/', views.verify_email, name='verify_email'),
    path('password_reset/', views.password_reset_view, name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/', views.password_reset_confirm_view, name='password_reset_confirm'),
]

CJob/urls.py
from django.urls import path
from . import views
app_name = 'CJob'

urlpatterns = [
    path('', views.home, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
]

FYP_Project/urls.py
from django.urls import path, include
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", lambda request: redirect('login/')),  # redirect to login
    path("MainApp/", include("MainApp.urls")),
    path('login/', include('Authentication.urls')),
]

MainApp/urls.py
from django.urls import path
from . import views

app_name = 'MainApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload_view, name='upload'),
    path('favorites/', views.favorites_view, name='favorites'),
    path('profile/', views.profile_view, name='profile'),
    path('jobs/', views.jobs_view, name='jobs'),
    path('cvs/<file_name>', views.load_file, name='load-file'),
    path('get-schools/', views.get_schools, name='get-schools'),
    path('get-jobs/', views.get_jobs, name='get-jobs'),
    path('find_jobs/', views.find_jobs, name='find-jobs'),
    path('show_jobs/', views.show_jobs, name='show-jobs'),
    path('favorite_job/', views.favorite_job, name='favorite-job'),
]

MainApp/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models
from django.conf import settings
from django.forms import modelformset_factory

from Authentication.models import CustomUser


class Job(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    detail_url = models.URLField()

    def __str__(self):
        return self.name


class DetailedJob(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    med_salary = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    formatted_work_type = models.CharField(max_length=255, null=True, blank=True)
    location = models.CharField(max_length=255, null=True, blank=True)
    remote_allowed = models.BooleanField(default=False)
    job_posting_url = models.URLField()
    application_type = models.CharField(max_length=100, null=True, blank=True)
    skills_desc = models.TextField(null=True, blank=True)
    work_type = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.title


class Resume(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='resume')
    summary = models.TextField(blank=True, null=True)
    experience = models.TextField(blank=True, null=True)
    education = models.TextField(blank=True, null=True)
    skills = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Resume"


class Study(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    degree = models.CharField(max_length=100)
    school = models.CharField(max_length=255)


class Experience(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job_title = models.CharField(max_length=100)
    job_detail = models.TextField()
    job_duration = models.IntegerField(validators=[MinValueValidator(1)])


class CV(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    cv_file = models.FileField(upload_to='MainApp/cvs/')


class Preference(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    preference = models.CharField(max_length=100)


class School(models.Model):
    name = models.CharField(max_length=255, primary_key=True)

    def __str__(self):
        return self.name


class FavoriteJob(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job_url = models.URLField()
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    is_remote = models.BooleanField()

    def __str__(self):
        return self.title

templates/base_generic.html
<!-- base_generic.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            CJob
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <style>

        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 10px 20px;
            text-align: center;
        }


        main {
            padding: 20px;
            margin-bottom: 60px; /* Adjust this value based on the height of your footer */
        }


        footer {
            background-color: #333;
            color: #fff;
            padding: 10px 20px;
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
        }

        {# used for Authentication: login, register, password reset, password reset conform #}
        .base_container {
            max-width: 400px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        input[type="text"],
        input[type="password"],
        input[type="submit"],
        input[type="file"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }

        input[type="submit"] {
            background-color: #333;
            color: #fff;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #555;
        }


        .centered {
            text-align: center;
        }

        .container {
            padding: 20px;
        }


        {# used in show jobs' back button #}
        .back-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .back-button:hover {
            background-color: #f1f1f1;
        }

        .full-width-textarea {
            width: 100%;
            {#border: none;#}
            {#outline: none;#}
            {#resize: none;#}
        }


        {# used in profile.html to show form data #}
        .form-section {
            position: relative;
            border: 2px solid #ccc;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }

        .form-group-border {
            position: relative;
            border: 1px solid #ccc;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }

        .larger-select {
            font-size: 16px;
            height: auto;
            padding: 10px;
        }

        {# used in favourite.html and show_jobs.html to show jobs table #}
        .jobs-table {
            border-collapse: collapse;
            width: 100%;
        }

        .jobs-table th,
        .jobs-table td {
            border-bottom: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .jobs-table th {
            border-top: 1px solid #ddd;
        }

        .delete-button {
            position: absolute;
            top: 10px;
            right: 10px;
            cursor: pointer;
            color: red;
            font-weight: bold;
            font-size: 20px;
        }

        .ui-autocomplete {
            max-height: 100px;
            overflow-y: auto;
            overflow-x: hidden;
        }

        .ui-autocomplete .ui-menu-item {
            display: block;
            width: 100%;
            padding: 5px 10px;
            clear: both;
            font-weight: 400;
            line-height: 1.42857143;
            color: #333;
            white-space: nowrap;
        }

        .ui-autocomplete .ui-menu-item:hover {
            text-decoration: none;
            background-color: #f5f5f5;
        }

        .alert {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid transparent;
            border-radius: 4px;
        }

        .alert.success {
            color: #3c763d;
            background-color: #dff0d8;
            border-color: #d6e9c6;
        }

        .alert.error {
            color: #a94442;
            background-color: #f2dede;
            border-color: #ebccd1;
        }
        

        {# check box in index page #}
        .row {
            margin: 12px;
        }

        .btn-checkbox {
            display: none;
        }

        .btn-default {
            display: inline-block;
            padding: 20px 30px;
            margin: 2px;
            font-size: 18px;
            cursor: pointer;
            text-align: center;
            border: 2px solid #ccc;
            background-color: #f7f7f7;
            color: #333;
            border-radius: 4px;
            transition: all 0.3s;
        }

        .btn-default:hover {
            background-color: #e7e7e7;
            border-color: #adadad;
        }

        .btn-checkbox:checked + .btn-default {
            background-color: #007bff;
            color: white;
            border-color: #007bff;
        }

    </style>
</head>
<body>
<header>
    <h1>Welcome to CJob</h1>
</header>

<main>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="{% if message.tags %} alert {{ message.tags }} {% else %} alert {% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}
    {% endblock %}
</main>

<footer>
    <p>&copy; {% now "Y" %} CJob. All rights reserved.</p>
</footer>

<script>
    // get all messages
    const messageElements = document.querySelectorAll('.messages .alert');

    messageElements.forEach(messageElement => {
        // set time count for 5 seconds
        setTimeout(() => {
            messageElement.style.display = 'none';
        }, 5000);
    });
</script>

<script src="{% static 'select/js/select2.min.js' %}"></script>

</body>
</html>

templates/favorites.html
{% extends "base_generic.html" %}

{% block content %}
    <ul class="nav nav-pills nav-justified">
        <li role="presentation"><a href="{% url 'MainApp:index' %}">Home</a></li>
        <li role="presentation"><a href="{% url 'MainApp:profile' %}">Profile</a></li>
        <li role="presentation" class="active"><a href="{% url 'MainApp:favorites' %}">Favorites</a></li>
        <li role="presentation"><a href="{% url 'Authentication:login' %}">Logout</a></li>
    </ul>

    {% if favorite_jobs %}
        <table class="jobs-table">
            <thead>
            <tr>
                <th>Title</th>
                <th>Location</th>
                <th>Is_Remote</th>
                <th>Favourite</th>  
            </tr>
            </thead>
            <tbody>
            {% for job in favorite_jobs %}
                <tr>
                    <td><a href="{{ job.job_url }}">{{ job.title }}</a></td>
                    <td>{{ job.location }}</td>
                    <td>{{ job.is_remote }}</td>
                    <td>
                        <form method="post" action="{% url 'MainApp:favorites' %}">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ job.id }}">
                            <input type="hidden" name="is_favorited" value="true">
                            <input type="submit" value="Unfavorite">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No favorite jobs to display.</p>
    {% endif %}
{% endblock %}


    

templates/index.html
{#<!-- /index.html -->#}

{% extends "base_generic.html" %}

{% block content %}
    
    <ul class="nav nav-pills nav-justified">
        <li role="presentation" class="active"><a href="{% url 'MainApp:index' %}">Home</a></li>
        <li role="presentation"><a href="{% url 'MainApp:profile' %}">Profile</a></li>
        <li role="presentation"><a href="{% url 'MainApp:favorites' %}">Favorites</a></li>
        <li role="presentation"><a href="{% url 'Authentication:login' %}">Logout</a></li>
    </ul>
    
    <div class="container">
        <form method="post" action="{% url 'MainApp:find-jobs' %}" id="jobSearchForm" class="form-section">
            {% csrf_token %}
            <label for="job-sites">Choose job sites:</label>
            <!-- ... -->
            <div class="row">
                <div class="col-lg-4">
                    <input type="checkbox" name="job_sites" id="indeedCheckbox" value="indeed" class="btn-checkbox"
                           aria-label="Indeed">
                    <label for="indeedCheckbox" class="btn btn-default">Indeed</label>
                </div><!-- /.col-lg-4 -->

                <div class="col-lg-4">
                    <input type="checkbox" name="job_sites" id="glassdoorCheckbox" value="glassdoor"
                           class="btn-checkbox" aria-label="Glassdoor">
                    <label for="glassdoorCheckbox" class="btn btn-default">Glassdoor</label>
                </div><!-- /.col-lg-4 -->

                <div class="col-lg-4">
                    <input type="checkbox" name="job_sites" id="linkedinCheckbox" value="linkedin" class="btn-checkbox"
                           aria-label="LinkedIn">
                    <label for="linkedinCheckbox" class="btn btn-default">LinkedIn</label>
                </div><!-- /.col-lg-4 -->
            </div>
            <!-- ... -->

            <div>
                <label for="address">Input your address:</label>
                <input type="text" id="address" name="address" placeholder="Enter your address" required>
            </div>
            <input type="submit" id="findJobsButton" value="Find Jobs">
        </form>
    </div>
    <script>
        document.getElementById('jobSearchForm').addEventListener('submit', function (event) {
            // Check if at least one site was selected
            var checkboxes = document.querySelectorAll('input[name="job_sites"]:checked');
            if (checkboxes.length === 0) {
                alert('Please select at least one job site.');
                event.preventDefault(); // Prevent form submission
            }
        });
    </script>


{% endblock %}

templates/jobs.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h1>Job Listings</h1>
    {% if jobs %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Detail</th>
            </tr>
        </thead>
        <tbody>
            {% for job in jobs %}
            <tr>
                <td>{{ job.name }}</td>
                <td>{{ job.description|truncatechars:100 }}</td>
                <td><a href="{{ job.detail_url }}" class="btn btn-detail" target="_blank">Detail</a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No jobs found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No jobs found.</p>
    {% endif %}
</div>
{% endblock %}

templates/login.html
<!-- /login.html -->

{% extends "base_generic.html" %}

{% block content %}
    <div class="base_container">
        <form method="post">
            {% csrf_token %}
            <h2 class="centered">Login to CJob</h2>
            {% if error_message %}
                {# set the error paragraph #}
                <p style="color: red;">{{ error_message }}</p>
            {% endif %}
            <input type="text" name="email" placeholder="Email" required>
            <input type="password" name="password" placeholder="Password" required>
            <div>
                <a href="{% url 'Authentication:password_reset' %}">Forgot password?</a>
            </div>
            <input type="submit" value="Sign In">
            <div>
                <a href="{% url 'Authentication:register' %}">Don't have an account? Register</a>
            </div>
        
        </form>
    </div>
{% endblock %}

templates/password_reset.html
<!-- templates/password_reset.html -->

{% extends "base_generic.html" %}

{% block content %}
<div class="base_container">
    <form method="post">
        {% csrf_token %}
        <h2 class="centered">Password Reset</h2>
        <input type="text" name="email" placeholder="Email" required>
        {# <button type="submit">Reset Password</button> #} 
        <input type="submit" value="Reset Password">
    </form>
    <a href="{% url 'Authentication:login' %}" class="button">Return to Login</a>
</div>
{% endblock %}

templates/password_reset_confirm.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="base_container">
        <h2 class="centered">Reset Password</h2>
        <form method="post">
            {% csrf_token %}
            <label for="id_new_password">New Password:</label><br>
            <input type="password" id="id_new_password" name="new_password"><br>
            <label for="id_confirm_password">Confirm Password:</label><br>
            <input type="password" id="id_confirm_password" name="confirm_password"><br>
            <input type="submit" value="Reset Password">
            {# <button type="submit">Reset Password</button> #}
        </form>
    </div>

{% endblock %}

templates/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset Email</title>
</head>
<body>
    <p>Hello {{ user.username }},</p>
    <p>You requested a password reset for your account. Please click the link below to reset your password:</p>
    <a href="{{ reset_link }}">{{ reset_link }}</a>
    <p>If you didn't request a password reset, please ignore this email.</p>
    <p>Regards,<br>CJob Team</p>
</body>
</html>

templates/profile.html
{#<!-- /profile.html -->#}
{% extends "base_generic.html" %}

{% block content %}
    <ul class="nav nav-pills nav-justified">
        <li role="presentation"><a href="{% url 'MainApp:index' %}">Home</a></li>
        <li role="presentation" class="active"><a href="{% url 'MainApp:profile' %}">Profile</a></li>
        <li role="presentation"><a href="{% url 'MainApp:favorites' %}">Favorites</a></li>
        <li role="presentation"><a href="{% url 'Authentication:login' %}">Logout</a></li>
    </ul>

    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-section">
                <h2>Study</h2>
                {{ study_form.as_p }}
            </div>

            <div class="form-section">
                <h2>Experience</h2>
                {{ experience_form.management_form }}
                <div id="experience-form-list">
                    {% for form in experience_form %}
                        <div class="form-group-border">
                            {{ form.as_p }}
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="form-section">
                <h2>CV</h2>
                {{ cv_form.as_p }}
            </div>


            <div class="form-section">
                <h2>Preference</h2>
                {{ preference_form.management_form }}
                <div id="preference-form-list">
                    {% for form in preference_form %}
                        <div class="form-group-border">
                            {{ form.as_p }}
                        </div>
                    {% endfor %}
                </div>
            </div>

            <button type="submit">Save Profile</button>
        </form>
    </div>

    <script>
        $(document).ready(function () {
            $('#id_school').autocomplete({
                source: '{% url 'MainApp:get-schools' %}',
                minLength: 2,
                open: function () {
                    setTimeout(function () {
                        $('.ui-autocomplete').off('menufocus hover mouseover mouseenter');
                    }, 0);
                }
            }).autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li class='dropdown-item'></li>")
                    .append("<div>" + item.label + "</div>")
                    .appendTo(ul);
            };
        });
        $(document).ready(function () {
            $('.preference-autocomplete').autocomplete({
                source: '{% url 'MainApp:get-jobs' %}',
                minLength: 2,
                open: function () {
                    setTimeout(function () {
                        $('.ui-autocomplete').off('menufocus hover mouseover mouseenter');
                    }, 0);
                }
            }).autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li class='dropdown-item'></li>")
                    .append("<div>" + item.label + "</div>")
                    .appendTo(ul);
            };
        });
    </script>


{% endblock %}

templates/register.html
<!-- templates/register.html -->

{% extends "base_generic.html" %}

{% block content %}
    <div class="base_container">
        <form method="post">
            {% csrf_token %}
            <h2 class="centered">Register to CJob</h2>
            {% if error_message %}
                <p style="color: red;">{{ error_message }}</p>
            {% endif %}
            <input type="text" name="email" placeholder="Email" required><br><br>
            <input type="password" name="password" placeholder="Password" required><br><br>
            <input type="password" name="confirm_password" placeholder="Confirm Password" required><br><br>
            <input type="submit" value="Register">
        </form>
        <a href="{% url 'Authentication:login' %}" class="button">Return to Login</a>
    </div>
{% endblock %}

templates/show_jobs.html
{% extends "base_generic.html" %}

{% block content %}
    <a href="{% url 'MainApp:index' %}" class="back-button">Back to Main Page</a>
    {% if jobs %}
        <table id="jobs-table" class="jobs-table">
            <thead>
            <tr>
                <th>Site</th>
                <th>Job Title</th>
                <th>Location</th>
                <th>Is_Remote</th>
                <th>Favourite</th>
            </tr>
            </thead>
            <tbody>
            {% for job in jobs %}
                <tr>
                    <td>{{ job.site }}</td>
                    <td><a href="{{ job.job_url }}">{{ job.title }}</a></td>
                    <td>{{ job.location }}</td>
                    <td>{{ job.is_remote }}</td>
                    <td>
                        <button class="favorite-btn{% if job.is_favorited_by_user %} favorited{% endif %}" data-job-url="{{ job.job_url }}" data-title="{{ job.title }}"
                                data-location="{{ job.location }}" data-is-remote="{{ job.is_remote }}">
                            {% if job.is_favorited_by_user %}Unfavorite{% else %}Favorite{% endif %}
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No jobs to display.</p>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script>
        $(document).ready(function () {
            $('#jobs-table').DataTable({
                "paging": false, 
            });
            $('.favorite-btn').click(function () {
                var btn = $(this);
                var jobUrl = btn.data('job-url');
                var title = btn.data('title');
                var location = btn.data('location');
                var isRemote = btn.data('is-remote');
                var isFavorited = btn.hasClass('favorited');
                $.ajax({
                    type: 'POST',
                    url: '{% url 'MainApp:favorite-job' %}',
                    data: {
                        'job_url': jobUrl,
                        'title': title,
                        'location': location,
                        'is_remote': isRemote,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'is_favorited': isFavorited
                    },
                    success: function (data) {
                        if (isFavorited) {
                            btn.removeClass('favorited').text('Favorite');
                        } else {
                            btn.addClass('favorited').text('Unfavorite');
                        }
                    },
                    error: function (xhr, textStatus, errorThrown) {
                        alert('Error: ' + errorThrown);
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/upload.html
{% extends "base_generic.html" %}

{% block title %}File Upload{% endblock title %}

{% block content %}
    <div class="base_container">
        <h2>Upload a File</h2>
        <form action="{% url 'file_upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="fileInput">Choose a file to upload:</label>
            <input type="file" id="fileInput" name="file" required>
            <input type="submit" value="Upload File">
        </form>
    </div>
{% endblock content %}

templates/verify_email.html
<!-- authentication/templates/verify_email.html -->

{% extends "base_generic.html" %}

{% block content %}
<div class="base_container">
    <form method="post">
        {% csrf_token %}
        <h2>Verify Your Email</h2>
        {% if error %}
            <p style="color: red;">{{ error }}</p>
        {% endif %}
        <input type="text" name="verification_code" placeholder="Enter Verification Code" required><br><br>
        <input type="submit" value="Verify">
    </form>
</div>
{% endblock %}